# Generated by Django 4.2.9 on 2026-03-12 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='CapitalInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('initial', 'Initial Capital'), ('additional', 'Additional Investment'), ('withdrawal', 'Capital Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, default='')),
                ('investment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capital Investment',
                'verbose_name_plural': 'Capital Investments',
                'db_table': 'capital_investments',
                'ordering': ['-investment_date'],
                'indexes': [models.Index(fields=['user', 'investment_date'], name='capital_inv_user_id_796568_idx')],
            },
        ),
    ]
