# Generated by Django 4.2.9 on 2026-03-13 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orderitem_product_capitalinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consignment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Steadfast Consignment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Steadfast Delivery Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Steadfast Tracking Code'),
        ),
        migrations.AlterField(
            model_name='capitalinvestment',
            name='investment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('utility', 'Utility Bills'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('salary', 'Salary'), ('advertisement', 'Advertisement'), ('marketing', 'Marketing'), ('delivery', 'Delivery'), ('shipping', 'Shipping'), ('packaging', 'Packaging'), ('purchase', 'Product Purchase'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20, verbose_name='Expense Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Expense Date'),
        ),
    ]
