# Generated by Django 4.2.9 on 2026-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_steadfast_fields_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierconfig',
            name='pathao_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Pathao Access Token'),
        ),
        migrations.AddField(
            model_name='courierconfig',
            name='pathao_is_sandbox',
            field=models.BooleanField(default=True, verbose_name='Pathao Sandbox Mode'),
        ),
        migrations.AddField(
            model_name='courierconfig',
            name='pathao_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Pathao Refresh Token'),
        ),
        migrations.AddField(
            model_name='courierconfig',
            name='pathao_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pathao Token Expires At'),
        ),
    ]
