# Generated by Django 4.2.9 on 2026-03-18 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_return_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created_at'], 'verbose_name': 'Return', 'verbose_name_plural': 'Returns'},
        ),
        migrations.AddField(
            model_name='order',
            name='return_description',
            field=models.TextField(blank=True, null=True, verbose_name='Return Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Sent'), ('not_delivered', 'Not Delivered'), ('size_issue', 'Size / Color Issue'), ('customer_request', 'Customer Request'), ('other', 'Other')], max_length=20, null=True, verbose_name='Return Reason'),
        ),
        migrations.AlterField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.order'),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Delivered'), ('not_delivered', 'Not Delivered'), ('size_issue', 'Size / Color Issue'), ('customer_request', 'Customer Request'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='return',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['user', 'status'], name='returns_user_id_b9ddd5_idx'),
        ),
    ]
