# Generated by Django 4.2.9 on 2026-03-19 06:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_return_reason_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_free_uses_remaining',
            field=models.IntegerField(default=3, help_text='Free AI order creation uses remaining', validators=[django.core.validators.MinValueValidator(0)], verbose_name='AI Free Uses Remaining'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wallet balance in BDT', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wallet Balance'),
        ),
        migrations.CreateModel(
            name='SubscriptionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly (৳200)'), ('yearly', 'Yearly (৳1099)'), ('wallet_topup', 'Wallet Top-up')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(help_text='bKash/Nagad transaction ID provided by user', max_length=100)),
                ('sender_number', models.CharField(blank=True, default='', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Purchase',
                'verbose_name_plural': 'Subscription Purchases',
                'db_table': 'subscription_purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('topup', 'Top-up'), ('sms', 'SMS Charge'), ('ai', 'AI Feature Charge'), ('package', 'Package Purchase'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, Negative = debit', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wallet_tran_user_id_5cf180_idx')],
            },
        ),
    ]
