# Generated by Django 4.2.9 on 2026-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_wallet_and_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='api_response',
            field=models.JSONField(blank=True, null=True, verbose_name='API Response'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost (BDT)'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='encoding',
            field=models.CharField(default='gsm7', help_text='gsm7 or unicode', max_length=10, verbose_name='Encoding'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='failure_reason',
            field=models.TextField(blank=True, default='', verbose_name='Failure Reason'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sms_parts',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='SMS Parts'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_sender_id',
            field=models.CharField(blank=True, default='', help_text='Registered sender ID on bulksmsbd.net', max_length=50, verbose_name='SMS Sender ID'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Recipient Phone'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
