# Generated by Django 4.2.9 on 2026-03-22 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sms_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ai_date',
            field=models.DateField(blank=True, help_text='Date when AI free uses were last reset', null=True, verbose_name='Last AI Use Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ai_free_uses_remaining',
            field=models.IntegerField(default=3, help_text='Free AI order creation uses remaining today (resets daily)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='AI Free Uses Remaining Today'),
        ),
    ]
